---
 # file is parsed by inner-most keys only
 data:
     debug: False
     batch_size: 5000
     num_workers: 8
     accumulate_batches: 1
     log_frequency: 10
 model:
     model: "mlp"
 train:
     patience: 10
     epochs: 10000
     min_epochs: 50
     lr: 5.e-5
     weight_decay: 1.e-6
     metric: "Val/de_auprc"

